INSERT INTO productos (nombre, precio, create_at) VALUES('Panasonic', 800, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Sony', 700, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Apple', 1000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('sony Notebook', 1000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Hewlett Packard', 500, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Bianichi', 600, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Nike', 100, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Adidas', 200, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Eeebok', 300, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Panasonic', 600, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Panasonic', 400, NOW());